LG-2173: Initial conversion to yarn/webpack     -  adds `webpacker` gem     -  adds webpack-dev-server to Procfile     -  moves existing application javascript to `app/javascripts`     -  abandons `app/assets/javascripts/selectizer.js`     -  removes `report_only` config from secure_headers csp config     -  includes localhost as needed in secure_headers csp config     -  updates `bin/setup`

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,29 +1,57 @@
-#!/bin/sh
+#!/usr/bin/env ruby
 
 # Set up Rails app. Run this script immediately after cloning the codebase.
 # https://github.com/thoughtbot/guides/tree/master/protocol
 
-# Exit if any subcommand fails
-set -e
+require 'pathname'
 
-# Set up Ruby dependencies via Bundler
-gem install bundler --conservative
-gem install foreman --conservative && gem update foreman
-bundle check || bundle install
-npm install
+# path to your application root.
+APP_ROOT = Pathname.new File.expand_path('../../',  __FILE__)
 
-# Copy application.yml
-cp config/application.yml.example config/application.yml
+def run(command)
+  # puts "command: #{command}"
+  abort "command failed (#{$?}): #{command}" unless system command
+end
 
-# Set up database and add any development seed data
-bin/rake dev:prime
+Dir.chdir APP_ROOT do
+  # This script is a starting point to setup your application.
+  # Add necessary setup steps to this file:
 
-# Add binstubs to PATH via export PATH=".git/safe/../../bin:$PATH" in ~/.zshenv
-mkdir -p .git/safe
+  puts %q{
 
-# Install node modules (e.g., style guide)
-npm ci
+            ______             _____
+            ___  /____________ ___(_)______   _______ _________   __
+            __  /_  __ \_  __ `/_  /__  __ \  __  __ `/  __ \_ | / /
+            _  / / /_/ /  /_/ /_  / _  / / /___  /_/ // /_/ /_ |/ /
+            /_/  \____/_\__, / /_/  /_/ /_/_(_)\__, / \____/_____/
+                       /____/                 /____/
+        ________              ______ ______                     _________
+        ___  __ \_____ __________  /____  /_____________ _____________  /
+        __  / / /  __ `/_  ___/_  __ \_  __ \  __ \  __ `/_  ___/  __  /
+        _  /_/ // /_/ /_(__  )_  / / /  /_/ / /_/ / /_/ /_  /   / /_/ /
+        /_____/ \__,_/ /____/ /_/ /_//_.___/\____/\__,_/ /_/    \__,_/
 
-# Only if this isn't CI
-# if [ -z "$CI" ]; then
-# fi
+
+  }
+
+  puts '== Copying application.yml =='
+  run 'test -L config/application.yml || cp -v config/application.yml.example config/application.yml'
+
+  puts "\n== Installing dependencies =="
+  run 'gem install bundler --conservative'
+  run 'gem install foreman --conservative && gem update foreman'
+  run 'bundle check || bundle install --without deploy production'
+  run 'yarn install'
+
+  puts "\n== Preparing database =="
+  run 'bin/rake db:create'
+  run 'bin/rake db:environment:set'
+  run 'bin/rake dev:prime'
+
+  puts "\n== Removing old logs and tempfiles =="
+  run 'rm -f log/*'
+  run 'rm -rf tmp/cache'
+
+  puts "\n== Add binstubs to PATH via export PATH=\".git/safe/../../bin:$PATH\" in ~/.zshenv =="
+  run 'mkdir -p .git/safe'
+end
